name: Deploy Scripts
on: push
jobs:
  job_1:
    name: Deploy SQL
    runs-on: self-hosted
    steps:
      - name: Step1
        uses: actions/checkout@v3
          with:
            ref: main
        run: |
          ls -al
          pwd
